// Pixel art for RestoreBound. Every sprite is a grid of palette letters drawn to a
// canvas at load. The style is chibi and cartoonish: big round heads, big eyes
// with a catchlight, rosy cheeks, soft three-tone shading lit from the top
// left, and a deep-navy outline instead of pure black so edges stay friendly.
// The hero, both siblings and both bosses are pixel versions of crayon
// drawings.

const PAL = {
  ".": null,
  // outline + neutrals
  "j": "#1b1a2e", "k": "#2c2b45", "q": "#6f6f86", "Q": "#4a4a62", "z": "#9d9db4",
  "e": "#d9d9e6", "E": "#a6a6bb", "w": "#fffdf7", "W": "#e6e2d6", "v": "#f6f3ea",
  // skin
  "s": "#ffd9c2", "S": "#e9ad8d", "h": "#fff0e4", "x": "#ffb3b3",
  // blonde hair
  "y": "#ffd85a", "Y": "#d9a92a", "i": "#fff0a8",
  // dark hair
  "d": "#2f2a4a", "D": "#1f1b36", "f": "#4a4470",
  // blues
  "b": "#4a8cf0", "B": "#2f62bd", "l": "#8fbcff",
  // reds
  "r": "#f0574c", "R": "#b53329", "c": "#d63d33", "C": "#8a1f18", "X": "#ff8c80",
  // pinks / magenta
  "m": "#ff77b8", "M": "#d64c90", "n": "#ffb0d8",
  // greens
  "g": "#66c96e", "G": "#3a9448", "L": "#7be05a", "K": "#43a83e", "V": "#b8f08a",
  // oranges / browns / yellows
  "o": "#ffa040", "O": "#d97018", "u": "#8a5a36", "U": "#5c3a1f", "t": "#ffd24a", "T": "#c9a021",
  // purples
  "p": "#c98ce6", "P": "#8f56b3",
  // cyan
  "a": "#5ad6cf", "A": "#2fa39c",
  // clown eyes (yellow-green)
  "1": "#e4de5a", "2": "#b3ad3c",
  // friends: lilac highlight, dark-blue hair, saber glow, saturn body, wood
  "N": "#e6c4f7", "Z": "#2a3f8f", "H": "#1b2a66", "4": "#5ad6cf66",
  "3": "#ffe3d2", "6": "#f2c3ad", "7": "#b07a4a",
};

function pixels(rows, pal = PAL) {
  const h = rows.length, w = Math.max(...rows.map((r) => r.length));
  const c = document.createElement("canvas");
  c.width = w; c.height = h;
  const ctx = c.getContext("2d");
  rows.forEach((row, y) => [...row].forEach((ch, x) => {
    const col = pal[ch];
    if (col) { ctx.fillStyle = col; ctx.fillRect(x, y, 1, 1); }
  }));
  return c.toDataURL();
}

// ---------------------------------------------------------------- hero (24 x 32)
// Chibi: big head, blonde swoop with a highlight, huge dark eyes with
// catchlights, rosy cheeks, white tee, blue shorts, sneakers with white soles.

const HERO = [
  "........jjjjjjjj........",
  "......jjyyiiyyyyjj......",
  ".....jyyiiiyyyyyyyj.....",
  "....jyyiiyyyyyyyyyyj....",
  "....jyyyyyyyyyyyyYyj....",
  "...jyYyyyyyyyyyyYYyyj...",
  "...jyYYjjjjjjjjjYYyyj...",
  "...jYjhhssssssssjjYyj...",
  "...jjhssssssssssssjjj...",
  "...jsssjjjssssjjjssssj..",
  "...jsssjwjssssjwjssssj..",
  "...jsssjjjssssjjjssssj..",
  "...jsxxsssssssssssxxsj..",
  "....jsssssjjjjjsssssj...",
  "....jSsssssjjjsssssSj...",
  ".....jSSsssssssssSSj....",
  "......jjSSSSSSSSSjj.....",
  ".....jjwwwwvvwwwwwjj....",
  "....jswwwwwvvwwwwwwsj...",
  "....jswwwwwwwwwwwwwsj...",
  "....jswwwwwwwwwwwwwsj...",
  "....js.wwwwwwwwwwww.sj..",
  "....jj.jWWWWWWWWWWj.jj..",
  ".......jbbbblbbbbbj.....",
  ".......jbbbbbbbbbbj.....",
  ".......jBBBBBBBBBBj.....",
  ".......jssssjjssssj.....",
  ".......jsssj..jsssj.....",
  ".......jSssj..jssSj.....",
  "......jjjjjj..jjjjjj....",
  ".....jkkkkkkjjkkkkkkj...",
  ".....jwwwwwwjjwwwwwwj...",
];

const HERO_SWORD = [
  "........jjjjjjjj........",
  "......jjyyiiyyyyjj......",
  ".jtj.jyyiiiyyyyyyyj.....",
  ".jujjyyiiyyyyyyyyyyj....",
  ".jujjyyyyyyyyyyyyYyj....",
  ".jujyYyyyyyyyyyyYYyyj...",
  "jEEEjYYjjjjjjjjjYYyyj...",
  "..jjYjhhssssssssjjYyj...",
  "...jjhssssssssssssjjj...",
  "...jsssjjjssssjjjssssj..",
  "...jsssjwjssssjwjssssj..",
  "...jsssjjjssssjjjssssj..",
  "...jsxxsssssssssssxxsj..",
  "....jsssssjjjjjsssssj...",
  "....jSsssssjjjsssssSj...",
  ".....jSSsssssssssSSj....",
  "......jjSSSSSSSSSjj.....",
  ".....jjwwwwvvwwwwwjj....",
  "....jswwwwwvvwwwwwwsj...",
  "....jswwwwwwwwwwwwwsj...",
  "....jswwwwwwwwwwwwwsj...",
  "....js.wwwwwwwwwwww.sj..",
  "....jj.jWWWWWWWWWWjjqj..",
  ".......jbbbblbbbbbjjqj..",
  ".......jbbbbbbbbbbj.j...",
  ".......jBBBBBBBBBBj.....",
  ".......jssssjjssssj.....",
  ".......jsssj..jsssj.....",
  ".......jSssj..jssSj.....",
  "......jjjjjj..jjjjjj....",
  ".....jkkkkkkjjkkkkkkj...",
  ".....jwwwwwwjjwwwwwwj...",
];

const HERO_GIANT = [
  "........jjjjjjjj........j...",
  "......jjyyiiyyyyjj.....jtj..",
  ".....jyyiiiyyyyyyyj....juj..",
  "....jyyiiyyyyyyyyyyj...juj..",
  "....jyyyyyyyyyyyyYyj...jUj..",
  "...jyYyyyyyyyyyyYYyyj..juj..",
  "...jyYYjjjjjjjjjYYyyj..juj..",
  "...jYjhhssssssssjjEEEEEEEEj.",
  "...jjhssssssssssssjEEEbEEj..",
  "...jsssjjjssssjjjssssj......",
  "...jsssjwjssssjwjssssj......",
  "...jsssjjjssssjjjssssj......",
  "...jsxxsssssssssssxxsj......",
  "....jsssssjjjjjsssssj.......",
  "....jSsssssjjjsssssSj.......",
  ".....jSSsssssssssSSj........",
  "......jjSSSSSSSSSjj.........",
  ".....jjwwwwvvwwwwwjj........",
  "....jswwwwwvvwwwwwwsj.......",
  "....jswwwwwwwwwwwwwsj.......",
  "....jsjwejwwwwwwwwwsj.......",
  "....jsjwejwwwwwwwww.sj......",
  "....jjjwejWWWWWWWWj.jj......",
  ".....jwejbbblbbbbbj.........",
  ".....jwejbbbbbbbbbj.........",
  "....jwejBBBBBBBBBBj.........",
  "....jwejssssjjssssj.........",
  "...jwejjsssj..jsssj.........",
  "...jwejjSssj..jssSj.........",
  "...jwejjjjjj..jjjjjj........",
  "..jwejkkkkkkjjkkkkkkj.......",
  "..jwejwwwwwwjjwwwwwwj.......",
  ".jwej.......................",
  ".jwej.......................",
  ".jjj........................",
  ".j..........................",
];

// ---------------------------------------------------------------- family (20 x 26)

const MOM = [
  ".......jjjjjjj......",
  ".....jjdddddddjj....",
  "....jdddfddddddjjj..",
  "...jdddjjjjjjjdddjj.",
  "...jddjhsssssjjddDj.",
  "...jdjsssssssssjdDj.",
  "...jdjsjjssjjsjjjj..",
  "....jsjwjssjwjsjj...",
  "....jsjjjssjjjsj....",
  "....jsxxsssssxxj....",
  "....jSssjjjjsssj....",
  ".....jSSssssSSj.....",
  "......jjSSSSjj......",
  ".....jjmmmmmmjj.....",
  "....jsmmnmmmmmsj....",
  "....jsmmmmmmmmsj....",
  "....jsmmmmmmmmsj....",
  "....js.mmmmmm.sj....",
  "....jj.mmmmmm.jj....",
  ".......jmmmmmmj.....",
  "......jmmmmmmmmj....",
  "......jMMMMMMMMj....",
  ".......jssjjssj.....",
  "......jjjjjjjjjj....",
  ".....jkkkkjjkkkkj...",
  ".....jjjjjjjjjjjj...",
];

// dad: dark hair, beard, worried frown, black vest over a white shirt
const DAD = [
  ".......jjjjjjj......",
  ".....jjdddddddjj....",
  "....jddddfddddddj...",
  "....jdjjjjjjjjjdj...",
  "....jjhssssssssjj...",
  "....jsssssssssssj...",
  "....jsjjjsssjjjsj...",
  "....jsjwjsssjwjsj...",
  "....jsjjjsssjjjsj...",
  "....jssssssssssdj...",
  "....jsddjjjjjddsj...",
  ".....jddjsssjddj....",
  "......jjdddddjj.....",
  ".....jjkkwwwkkjj....",
  "....jskkwwwwwkksj...",
  "....jskkwwjwwkksj...",
  "....jskkkwwwkkksj...",
  "....js.kkwwwkk.sj...",
  "....jj.jkkkkkj.jj...",
  ".......jkkkkkj......",
  ".......jkkkkkj......",
  ".......jQQQQQj......",
  ".......jssjssj......",
  "......jjjjjjjjj.....",
  ".....jkkkkjjkkkkj...",
  ".....jjjjjjjjjjjj...",
];

// little sister: black hair, side ponytail, pink top, white shorts
const SIS = [
  "......jjjjjjj.......",
  ".....jddfddddjj.....",
  "....jddfdddddddjj...",
  "....jddjjjjjjjdddj..",
  "....jdjhssssssjddj..",
  "....jjjssssssssjddj.",
  ".....jsjjssssjjsjdj.",
  ".....jsjwjssjwjsjDj.",
  ".....jsjjjssjjjsjj..",
  ".....jsxxssssxxsj...",
  ".....jSssjjjjsssj...",
  "......jSSssssSSj....",
  ".......jjSSSSjj.....",
  "......jjmmmmmmjj....",
  ".....jsmmnmmmmmsj...",
  ".....jsmmmnmmmmsj...",
  ".....jsmmmmmmmmsj...",
  ".....js.wwwwww.sj...",
  ".....jj.jWWWWj.jj...",
  "........jwwwwj......",
  "........jssjsj......",
  "........jssjsj......",
  ".......jjjjjjjj.....",
  "......jSSSjjSSSj....",
  "......jjjjjjjjjj....",
];

// little brother: short black hair, big eyes, blue shirt
const BRO = [
  "......jjjjjjj.......",
  ".....jddfdddddj.....",
  "....jddddddddddj....",
  "....jdjjjjjjjjdj....",
  "....jjhssssssssjj...",
  "....jsssssssssssj...",
  "....jsjjjsssjjjsj...",
  "....jsjwjsssjwjsj...",
  "....jsjjjsssjjjsj...",
  "....jsxxsssssxxsj...",
  "....jSsssjjjjsssj...",
  ".....jSSssssssSj....",
  "......jjSSSSSjj.....",
  ".....jjbbbbbbbjj....",
  "....jsbbblbbbbbsj...",
  "....jsbbbbbbbbbsj...",
  "....jsbbbbbbbbbsj...",
  "....js.bbbbbbb.sj...",
  "....jj.jBBBBBj.jj...",
  ".......jssjssj......",
  ".......jssjssj......",
  ".......jssjssj......",
  "......jjjjjjjjj.....",
  ".....jSSSjjjSSSj....",
  ".....jjjjjjjjjjj....",
];

// cats (18 x 14): round, big eyes, pink inner ears, curled tail
const CAT_ORANGE = [
  "..jj..........jj..",
  ".joxj........jxoj.",
  ".jooxj......jxooj.",
  ".jooojjjjjjjjoooj.",
  "..joooooooooooooj.",
  "..jojjooooooojjoj.",
  "..jjwjoooooojwjjj.",
  "..jojjooojooojjoj.",
  "...jooooOoooooj...",
  "...joOooooooOoj.jj",
  "....jooooooooojjoj",
  "....jooojjoooooooj",
  "....joojj.jooojjj.",
  "....jjjj..jjjj....",
];
const CAT_GREY = [
  "..jj..........jj..",
  ".jqxj........jxqj.",
  ".jqqxj......jxqqj.",
  ".jqqqjjjjjjjjqqqj.",
  "..jqqqqqqqqqqqqqj.",
  "..jqjjqqqqqqqjjqj.",
  "..jjwjqqqqqqjwjjj.",
  "..jqjjqqqjqqqjjqj.",
  "...jqqqqQqqqqqj...",
  "...jqQqqqqqqQqj.jj",
  "....jqqqqqqqqqjjqj",
  "....jqqqjjqqqqqqqj",
  "....jqqjj.jqqqjjj.",
  "....jjjj..jjjj....",
];

// ---------------------------------------------------------------- townsfolk (20 x 26)

const ELDER = [
  ".......jjjjjj.......",
  ".....jjeeeeeejj.....",
  "....jeeezeeezeeej...",
  "...jeeejjjjjjjeeej..",
  "...jeejhsssssjeeej..",
  "...jeejssssssssjej..",
  "...jeejsjjssjjsjej..",
  "...jjjsjwjssjwjsjj..",
  ".....jsjjjssjjjsj...",
  ".....jsxxsssssxxj...",
  ".....jsseeeeeessj...",
  "......jeeeeeeeej....",
  ".......jjeeeejj.....",
  "......jjGGGGGGjj....",
  ".....jsGGGgGGGGsj...",
  ".....jsGGGGGGGGsj...",
  ".....jsGGGGGGGGsj...",
  ".....js.GGGGGG.sj...",
  ".....jj.GGGGGG.jj...",
  "........jGGGGj......",
  "........jGGGGj......",
  "........jUUUUj......",
  "........jssjssj.....",
  ".......jjjjjjjjj....",
  "......jkkkkjjkkkj...",
  "......jjjjjjjjjjj...",
];

const KID = [
  ".......jjjjjj.......",
  ".....jjoooooojj.....",
  "....jooOooooOoooj...",
  "....joojjjjjjjooj...",
  ".....jhssssssssj....",
  ".....jsssssssssj....",
  ".....jsjjsssjjsj....",
  ".....jsjwjssjwjsj...",
  ".....jsjjjssjjjsj...",
  ".....jsxxsssssxxj...",
  ".....jSssjjjjsssj...",
  "......jSSssssSSj....",
  ".......jjSSSSjj.....",
  "......jjaaaaaajj....",
  ".....jsaaawwaaasj...",
  ".....jsaaaaaaaasj...",
  ".....jsaaaaaaaasj...",
  ".....js.aaaaaa.sj...",
  ".....jj.jbbbbj.jj...",
  "........jbbbbj......",
  "........jssjsj......",
  "........jssjsj......",
  ".......jjjjjjjj.....",
  "......jkkkkjjkkkj...",
  "......jjjjjjjjjjj...",
];

const DOG = [
  "..jjjj..............jj..",
  ".jddddj............jSSj.",
  "jddddddjjjjjjjjjjjjSSSj.",
  "jdddSSSSSSSSSSSSSSSSSSj.",
  "jddSjSSsssSSSSSSSSSSSj..",
  "jdSSSSSssSSSSSSSSSSSj...",
  "jSSSSSSSSSSSSSSSSSSSSj..",
  "jSSjjSSSSSSSSSSSSSSSSSj.",
  ".jSSSSSSSSSSSSSSSSSSSSj.",
  ".jSjjjSSSSSSSSSSSSSSSj..",
  "..jSmSSSSSSSSSSSSSSSj...",
  "...jjSSjjjjjSSjjjjSSj...",
  ".....jSj...jSj..jSj.....",
  ".....jSj...jSj..jSj.....",
  ".....jSj...jSj..jSj.....",
  ".....jjj...jjj..jjj.....",
];

// ---------------------------------------------------------------- BUGON (52 x 40)
// Mini boss. The yellow Y on the crayon drawing is read as a blaze marking:
// two big glossy dark eyes with catchlights sit in the arms of the Y, the
// stem runs down to a small nose and a pouty mouth, and heavy angled brows
// give it the bad attitude. Huge floppy ears with pink insides, a gloss on
// the head, skinny red body with arms flung out, yellow legs and feet.

const BUGON = [
  ".........................jjjjjjj........................",
  ".......jjjjjjjj.......jjjXRRRRRRjjj.......jjjjjjjj......",
  ".....jjRRRRRRRRjj...jjXXXXRRRRRRRRRjj...jjRRRRRRRRjj....",
  "....jRRRRRRRRRRRRj.jXXXXRRRRRRRRRRRRRj.jRRRRRRRRRRRRj...",
  "...jRRRRRnnnnnnnnRjjjXXRRRRRRRRRRRRRjjjRnnnnnnnnRRRRRj..",
  "..jRRRRRnnnnnnnnnRCCCjjjRRRRRRRRRjjjRCCCnnnnnnnnnRRRRRj.",
  "..jRRRRnnnnnnnnnnRCCCCCCjjRRRRRjjCCCCCCCnnnnnnnnnnRRRRj.",
  ".jRRRRRnnnnnnnnnRRRRCjjjCCCRRRRCCCjjjCRRRnnnnnnnnnRRRRRj",
  "..jRRRRRnnnnnnnnRRRRjwwwjjjRRRRjjjwwwjRRRnnnnnnnnRRRRRj.",
  "..jRRRRRRnnnnnnnRRRRjwwwhwwjRRjwhwwwwjRRRnnnnnnnRRRRRRj.",
  "...jCCCCCCCCCCCCRRRRjwwwjjwjRRjwjjwwwjRRRCCCCCCCCCCCCj..",
  "....jCCCCCCCCCCCRRRRjwwwjjwjRRjwjjwwwjRRRCCCCCCCCCCCj...",
  ".....jjCCCCCCCCjRRRRjwwwjjwjtRjwjjwwwjRRRjCCCCCCCCjj....",
  ".......jjjjjjjj.jRRRRjwwjjjttttjjjwwjRRRj.jjjjjjjj......",
  "................jRRRRRjjRRtttttttRjjRRRRj...............",
  ".................jRRRRRRRRRtttttRRRRRRRj................",
  ".................jCCCCCCCCCttttCCCCCCCCj................",
  "..................jCCCCCCCCtttCCCCCCCCj.................",
  "...................jCCCCCCCjjjCCCCCCCj..................",
  "....................jjCCCCjjjjjCCCCjj...................",
  "......................jjjCCtttCCjjj.....................",
  ".........................jCjrjCj........................",
  ".............jjj.........jrrrrrj...........jjj..........",
  ".............jjrjj......jrrrrrrrj........jjrjj..........",
  "...............jjrjj...jrrrrrXXrrj.....jjrjj............",
  ".................jjrjjjrrrrrrrrrrrj..jjrjj..............",
  "...................jjrrrrrrrrrrrrrrjjrjj................",
  ".....................jrrrrrrrrrrrrrjjj..................",
  "......................jrrrrrrrrrrrj.....................",
  "......................jrrrrrrrrrrrj.....................",
  ".......................jrrrrrrrrrj......................",
  "........................jrrrrrrrj.......................",
  "........................jttjrjttj.......................",
  "........................jtj.j.jtj.......................",
  "........................jtj...jtj.......................",
  "........................jtj...jtj.......................",
  "........................jtj...jtj.......................",
  "........................jtj...jtj.......................",
  ".......................jtttj.jtttj......................",
  ".......................jjjjj.jjjjj......................",
];

// ---------------------------------------------------------------- LYGON (46 x 46)
// Final boss. Big round white face, three fluffy green tufts, yellow-green
// almond eyes with pupils and catchlights, glossy red ball nose, a wide red
// grin full of teeth, orange shirt under a huge black spiky-shouldered jacket
// with shading, black trousers, grey shoes.

const LYGON = [
  "......................jjjj......................",
  ".....................jLLLVj.....................",
  "....................jLLVLLLj....................",
  "....jjjj............jLLLLLLj............jjjj....",
  "...jLLVLj...........jLKLLLKj...........jLVLLj...",
  "..jLLVLLLj.........jjjjjjjjjj.........jLLLVLLj..",
  "..jLLLLLLj......jjjwwwwwwwwwwjjj......jLLLLLLj..",
  "..jLKLLLKj....jjwwwwwwwwwwwwwwwwjj....jKLLLKLj..",
  "...jjjjj.....jwwwwwwwwwwwwwwwwwwwwj.....jjjjj...",
  "............jwwwwwwwwwwwwwwwwwwwwwwj............",
  "...........jwwwwwwwwwwwwwwwwwwwwwwwwj...........",
  "...........jwwwww1111wwwwwwww1111wwwj...........",
  "..........jwwwww111j11wwwwww11j111wwwwj.........",
  "..........jwwwww11jjj1wwwwww1jjj11wwwwj.........",
  "..........jwwwww11jwj1wwwwww1jwj11wwwwj.........",
  "..........jwwwwww1jjj2wwwwww2jjj1wwwwwj.........",
  "..........jwwwwwww2222wwwwwwww2222wwwwj.........",
  "..........jwwwwwwwwwwwwjrrjwwwwwwwwwwwj.........",
  "..........jwwwwwwwwwwwjrXrrjwwwwwwwwwwj.........",
  "..........jwwwwwwwwwwwjrrrrjwwwwwwwwwwj.........",
  "..........jwwwwwwwwwwwwjRRjwwwwwwwwwwwj.........",
  "...........jwwwjcccccccccccccccjwwwwwj..........",
  "...........jwwjccwcwcwcwcwcwcwccjwwwwj..........",
  "............jwjcccccccccccccccccjwwwj...........",
  ".............jwjcccccccccccccccjwwwj............",
  "..............jwjjCcccccccccCjjwwwj.............",
  "...............jwwwjjjjjjjjjjwwwwj..............",
  "................jjwwwwwwwwwwwwwjj...............",
  "..................jjjwwwwwwwjjj.................",
  ".......jjjjj.........jwooooowj.........jjjjj....",
  "......jkkkkkjj.......jwoooOowj.......jjkkkkkj...",
  ".....jkkkkkkkkjj.....jwooooowj.....jjkkkkkkkkj..",
  "....jkkkkkkkkkkkjjjjjjwoooOowjjjjjjkkkkkkkkkkkj.",
  "...jkkkkkkkkkkkkkkkkkkjooooojkkkkkkkkkkkkkkkkkkj",
  "..jkkkkjkkkkkkkkkkkkkkjoooojkkkkkkkkkkkkkkjkkkkj",
  ".jkkkkjjkkkkkkkkkkkkkkkjoojkkkkkkkkkkkkkkkjjkkkkj",
  "jkkkkjj.jkkkkkkkkkkkkkkjjjjkkkkkkkkkkkkkkj.jjkkkkj",
  "jkkkjj..jkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkj..jjkkkj",
  ".jjj....jkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkj....jjj.",
  "........jkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkj........",
  ".........jkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkj.........",
  "..........jjjjjjjkkkkkkkjjjkkkkkkkjjjjjj..........",
  ".................jkkkkkkj.jkkkkkkj................",
  ".................jkkkkkkj.jkkkkkkj................",
  ".................jkkkkkkj.jkkkkkkj................",
  "..............jjjjzEEEEEjjjEEEEEzjjjj.............",
  ".............jzEEEEEEEEEjjjEEEEEEEEEzj............",
  ".............jjjjjjjjjjjj.jjjjjjjjjjjj............",
];

// ---------------------------------------------------------------- cave enemies (generated)
// Pixel versions of six numbered crayon drawings: two animals-ish, two
// aliens, three robots, plus the cave mouth on the hill.

const CHOMPO = [
  ".........www.........www........",
  "........wwwww.......wwwww.......",
  ".......wwhjjww..j..wwhjjww......",
  ".......wwjjjjwjjmjjwwjjjjw......",
  ".......wwjjjjwjmmmjwwjjjjw......",
  ".......jwwjjwjnnnmmjwwjjwj......",
  "......jmjwwwjnnnnnnmjwwwjmj.....",
  ".....jmmnjjjnnnnnnnmmjjjmmmj....",
  "....jmmnnnnnnnnnnnnnmmmmmmmmj...",
  "....jmmmnnnnnnnnnnnmmmmmmmmmj...",
  "....jmmmnjnnjjjjjjjjjjmmmmmmj...",
  "...jmmmmjwjjwjjwjjwjjwjmmmmmmj..",
  "....jmmmjwjjwjjwjjwjjwjjjmmmj...",
  "....jmmmjjjjjjjjjjjjjjjjjmmmj...",
  "....jmmjjjjjjjjjMjjjjjjjjjmmj...",
  ".....jmmjjjMMMMMMMMMMMjjjmmj....",
  "......jmjjjMMMMMMMMMMMMjjmj.....",
  ".......jmjwjMMMMMMMMMMjmmj......",
  "........jmjmjjjjMjjjjmmmj.......",
  ".....jjjbbbjjjjjmjjjjjbbbjjj....",
  ".....jbbbbj.....j.....jbbbbj....",
  ".....jbbbbj...........jbbbbj....",
  "....jjjjjjjj.........jjjjjjjj...",
];

const ZAGG = [
  "................j...............",
  "...........jjjjjbjjjjj..........",
  "........jjjblbbbbbbbbbjj........",
  "........jBjjjjjlbbbbbbbbj.......",
  ".......jBBBBBBBjjjbbbbbbbj......",
  "......jlllljjjBBBBjjjbbbbbj.....",
  ".....jbllljwwwjjjjjBBBbbbbbj....",
  ".....jllljwwwwwwwwwjjBbbbbbj....",
  "....jbblljwwwwhhjjwwwjbbbbbbj...",
  "....jbblljwwwwjjjjjwwjbbbbbbj...",
  "....jbbbjwwwwwjjjjjwwwjbbbbbj...",
  "....jbbbbjwwwjjjjjjjwjbbbbbbj...",
  "...jbbbbbjwwwwjjjjjwwjbbbbbbbj..",
  "....jbbbbjwwwwjjjjjwwjbbbbbbj...",
  "....jbbbbbjwwwwjjjwwjbbbbbbbj...",
  "...jbbbbbbbjwwwwwwwjbbbbbbbbbjj.",
  "..jbjbbbbbbbjjjwjjjbbbbbbbbbjjbj",
  "..jj.jbbbbbbbbbjbbbbbbbbbbbj..jj",
  ".jbjjjbbbbjjbbbbjjbbbbjjbbbbjjbj",
  "jbj.jjjjbjjjjjbjjjjjbjjjjjbjjjjj",
  "jj...jwwjjjjwwjjjjwwjjjjwwjjj..j",
  "......jjjjbbjjjjbbjjjjbbjjjj....",
  ".......jjjjbbjjbbbbjjbjj.jj.....",
  "...........jjjjjbjjjjj..........",
  "................j...............",
  "..........jjjj.....jjjj.........",
  "..........jBBj.....jBBj.........",
  "..........jBBj.....jBBj.........",
  "..........jjjj.....jjjj.........",
];

const SKITTER = [
  "...........................jjj......",
  "...........................jjj......",
  "..........................j.........",
  ".........................j..........",
  "...................j....j...........",
  "............jjjjjjjpjjjjpjj.........",
  ".........jjjPPjPPPPPjpppppjjjj......",
  "....j..jjPPPPjwjPPPjwjPppjwjppjj....",
  ".jjjtjjPPPPPPPjPPPPPjPPPppjpppppj...",
  "..jijwjkkkkkkPPPPPPPPPPpppppppppj...",
  ".jtttjttQQQQkPPPPPPPPppppppppppppj..",
  "..jttttQQQQQkppPppppppppppppppppj...",
  ".jjjtjjkkkkkkpppppppppppppppppppj...",
  "....j..jjpppppppppppppppppppppjj....",
  ".........jpppppppppppppppppjpj......",
  "..........jQQpjjQQQpjjQQQpj.jQj.....",
  "..........jQQj..jQQj..jQQj..jQQj....",
  ".........jQjQj.jQjQj.jQjQj.jQjQj....",
  "........jQj.jQjQj.jQjQj.jQjQj.jj....",
  "........jj..jjjj..jjjj..jjjj..jjj...",
];

const WIBBLO = [
  ".......jjj.........jjj......",
  ".......jtj.........jtj......",
  "........j...........j.......",
  ".........j.........j........",
  "........j...........j.......",
  ".........j.........j........",
  "........j.....j.....j.......",
  ".........jjjjjnjjjjj........",
  "........jjjhjjjnnnnnj.......",
  ".......jhhhhhhhjnnnnnj......",
  "......jhhhhhhhhhjnnnnnj.....",
  "......jhhhhhhhhhjnnnnnj.....",
  ".....jhhhhhhhhhhhjjnnnnj....",
  ".....jjhhhwhhhwhjjwjnnnj....",
  ".....jjhhwwwhwwwjwwwjnnj....",
  "....jnnjhwwwhwwwjwwwjnnnj...",
  ".....jnnjwjwjwjwjwjwjnnj....",
  ".....jnnnjwjnjwjnjwjnnnj....",
  ".....jnnnnjnnnjnnnjnnnnj....",
  "......jnnnjnnnnnnnjnnnj.....",
  "......jnnnnjjjjjjjnnnnj.....",
  ".......jnnnnnnnnnnnnnj......",
  "........jjnnnnnnnnnjj.......",
  "..........jjjjnnjjj.........",
  "......j...j...jj...j........",
  "......j....j....j..j........",
  "......j...j....j...j........",
  ".....j.....j....j...j.......",
  ".....j....j....j....j.......",
  ".....j.....j....j...j.......",
  "....j.....j....j.....j......",
];

const REDSTACK = [
  "...........jjj..........",
  "...........jtj..........",
  "............j...........",
  "......jjjjjjrjjjjj......",
  "......jXXXrrrrrrrj......",
  "......jXkkkkkkkkrj......",
  "......jXkaakkaakrj......",
  "......jXkkkkkkkkrj......",
  "......jXXXrrrrrrrj......",
  "......jRRRRRRRRRRj......",
  "......jXXXrrrrrrrj......",
  "......jrrrrrrrrrrj......",
  "......jccccccccccj......",
  ".jjjjjcXXXccccccccjjjjj.",
  ".jRRRRcXXXccccccccRRRRj.",
  ".jRRRRcXXXccccccccRRRRj.",
  ".jRRjjcXXXccccccccjjRRj.",
  "jccj..jXXXcccccccj..jccj",
  "jccj..jRRRRRRRRRRj..jccj",
  "jccj..jXXXcccccccj..jccj",
  "jjjj..jccccccccccj..jjjj",
  "......jrrrrrrrrrrj......",
  "......jXXXrrrrrrrj......",
  "......jXXXrrrrrrrj......",
  "......jXXXrrrrrrrj......",
  "......jXXXrrrrrrrj......",
  "......jXXXrrrrrrrj......",
  "......jRRRRRRRRRRj......",
  "......jXXXrrrrrrrj......",
  "......jrrrrrrrrrrj......",
  "....jjQQQQQQQQQQQQjj....",
  "....jqqqqqqqqqqqqqqj....",
  "....jqqqqqqqqqqqqqqj....",
  "...jQQQQQQQQQQQQQQQQj...",
  "...jQQQQQQQQQQQQQQQQj...",
  "...jQQQQQQQQQQQQQQQQj...",
  "...jQQkQQkQQkQQkQQQQj...",
  "...jjjjjjjjjjjjjjjjjj...",
];

const BOXOR = [
  "......................j.....................",
  ".....................jrj....................",
  "...................jjrrrjj..................",
  "...................jkrrrkj..................",
  "...................jkkrkkj..................",
  "................jjjkkkkkkkjjj...............",
  "..............jjkQQkkkkkkkkkkjj.............",
  "............jjkQQQQQQQQQQQkkkkkjj...........",
  "...........jkkQQQQQQQQQQQQQkkkkkkj..........",
  "...........jkkkQQQQQQQQQQQkkkkkkkj..........",
  "..........jkkkkkkQQQQQQQkkkkkkkkkkj.........",
  "...........jkkkkkkkkkkkkkkkkkkkkkj..........",
  ".........jjkkkkkkkkkkkkkkkkkkkkkkkj.........",
  ".........jnnkkkkkkkkkkkkkkkkkkkkknj.........",
  ".........jnnnnkkkkkkkkkkkkkkkkknnnj.........",
  ".........jPPjPPPkkkkjjjjjkkkkppjppj.........",
  "..jjjjjjjpPjwjPPppjjwwwwwjjpppjwjppjjjjjjj..",
  "..jPPPPPPpPPjPPPpjwwwwwwwwwjpppjpppPPPPPPj..",
  "..jPPPPPPpPPPPPPjwwwjjjjjwwwjppppppPPPPPPj..",
  "..jPPPPPPpPPPPPPjwwjjjrrrjwwjppppppPPPPPPj..",
  "..jPPPPPPpPPPPPjwwjjhhjrrrjwwjpppppPPPPPPj..",
  "..jPPPPPPpPPPPPjwwjrjjrCrrjwwjpppppPPPPPPj..",
  "..jPPPPjjpPPPPPjwwjrrrCCCrjwwjpppppjjPPPPj..",
  "jjppppj..jPPPPPjwwjrrCCCCCjwwjppppj..jppppjj",
  "jpppppj..jPPPPPjwwjrrrCCCrjwwjppppj..jpppppj",
  "jpppppj..jPPPPPPjwwjrrrCrjwwjpppppj..jpppppj",
  "jpppppj..jPPPPPPjwwwjjjjjwwwjpppppj..jpppppj",
  "jppjjpj..jPPPPPPpjwwwwwwwwwjppppppj..jppjjpj",
  ".jj..jj..jPPPPPPppjjwwwwwjjpppppppj...jj..jj",
  ".jj..jj..jPPkkkkkkkkjjjjjkkkkkkkppj...jj..jj",
  "jkj..jkj.jPPkqQQQqQQQqQQQqQQQqkkppj...jj..jj",
  "jj....jj.jPPjkkkkkkkkkkkkkkkkkkjppj..jkj..jj",
  "jj....jj.jPjwjPPppppppppppppppjwjpj..jj....j",
  "jj....jj.jPPjPPPpppppppppppppppjppj..jj....j",
  ".........jjjppppppppjjjjppppppppjjj.........",
  "............jQQQQQQj....jQQQQQQj............",
  "............jQQQQQQj....jQQQQQQj............",
  "............jQQQQQQj....jQQQQQQj............",
  "............jQQQQQQj....jQQQQQQj............",
  "............jQQQQQQj....jQQQQQQj............",
  "............jQQQQQQj....jQQQQQQj............",
  "............jQQQQQQj....jQQQQQQj............",
  "...........jkkkkkkkkj..jkkkkkkkkj...........",
  "...........jjjjjjjjjj..jjjjjjjjjj...........",
];

const CAVEMOUTH = [
  "........................j.......................",
  ".................jjjjjjjqjjjjjjj................",
  "..............jjjqqqqqqqqqqqqqqqjjj.............",
  "...........jjjqqqqqqqqqqqqqqqqqqqqqjjj..........",
  ".........jjqqqqqqqqqzqqqqqqqqqqqqqqqqqjj........",
  "........jqqqqqzzzzzzzzzzzzzqqqqqqqqqqqqqj.......",
  ".......jQqqzzzzzzzzzzzzzzzzzzzqqqqqqqqqqqj......",
  "......jQQQQzzzzzzzzzzzzzzzzzzzzzqqqqqqqqqqj.....",
  ".....jQQQQQQzzzzzzzzzzzzzzzzzzzzzqqqqqQqqqqj....",
  "....jqQQQQQzzzzzzzzzzzzzzzzzzzzzzzqqQQQQQqqqj...",
  "...jqqzzQzzzzzzzzzzzzzzzkzzzzzzzzzzQQQQQQQqqqj..",
  "..jqqzzzzzzzzzzzzzzzkkkkkkkkkzzzzzzzQQQQQqqqqqj.",
  "..jqqzzzzzzzzzzzzzkkkkkkkkkkkkkzzzzzqqQqqqqqqqj.",
  ".jqqqzzzzzzzzzzzzkkkkkkkkkkkkkkkzzzzqqqqqqqqqqqj",
  ".jqqzzzzzzzzzzzzkkkkkkkkkkkkkkkkkzzzzqqqqqqqqqqj",
  ".jqqqzzzzzzzzzzkkkkkkkkkjkkkkkkkkkzzqqqqqqqqqqqj",
  ".jqqqzzzzzzzzzzkkkkkkjjjjjjjkkkkkkzzqqqqqqqqqqqj",
  ".jqqqzzzzzzzzzkkkkkjjjjjjjjjjjkkkkkzqqqqqqqqqqqj",
  "jqqqqqQzzzzzzzkkkkjjjjjjjjjjjjjkkkkqqqqqqqqqqqqj",
  ".jqqQQQQQzzzzkkkkkjjjjjjjjjjjjjkkkkkqqqqqqqqqqqj",
  ".jqQQQQQQQzzzkkkkjjjjjjjjjjjjjjjkkkkqqqqQqqqqqqj",
  ".jqqQQQQQzzzzkkkjjjjjjjjjjjjjjjjjkkkqqQQQQQqqqqj",
  ".jqqqqQqqqqzzkkkjjjjjjjjjjjjjjjjjkkkqQQQQQQQqqqj",
  ".jqqqqqqqqqqqkkkjjjjjjjjjjjjjjjjjkkkqqQQQQQqqqqj",
  "..jqqqqqqqqqkkkkjjjjjjjjjjjjjjjjjkkkkqqqQqqqqqj.",
  "..jqqqqqqqqqqkkkjjjjjjjjjjjjjjjjjkkkqqqqqqqqqqj.",
  "...jqqqqqqqqQkkjjjjjjjjjjjjjjjjjjjkkqqqqqqqqqj..",
  "....jqqqqqQQQkkkjjjjjjjjjjjjjjjjjkkkQqqqqqqqj...",
  ".....jqqqQQQQkkkjjjjjjjjjjjjjjjjjkkkQQQqqqqj....",
  "......jqqqQQQkkkjjjjjjjjjjjjjjjjjkkkQQQQqqj.....",
  ".......jqqqqQqkkjjjjjjjjjjjjjjjjjkkQQQQqqj......",
  "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
];

// ---------------------------------------------------------------- the Hollow (generated)
// Pixel versions of the second crayon page: the purple orb in its golden
// stand, Malva the horned sorceress, five winged swoopers and four boxy
// stompers (corrupted townsfolk with hollow eyes and red mouths), and the
// gate into the Hollow. Built from shaded shapes with an auto outline.

// the Hollow orb: glossy purple ball with a swirl in a golden three-pronged stand (26 x 36)
const ORB = [
  "..........................",
  "..........jjjjjjj.........",
  "........jjPPPPPPPjj.......",
  "......jjpppppPPPPPPj......",
  "......jpppppppPPPPPfj.....",
  "...jjjppwwwpnnnnPPPPfjjj..",
  "..jtijpwwwwwnppPnnPPfjttj.",
  "..jtjPppwwwppppPPPnPPfjTj.",
  "..jijPppwppppppppPPPPfjTj.",
  "..jijPpppppppppPppPPPfjTj.",
  "..jijPPpppppppPPPpPPPfjtj.",
  "..jijPPPpppppPPPPpPPPfjtj.",
  "..jijPPPPpfPPPPPPfPPffjtj.",
  "..jtjPPPPPPffPPPffPPffjTj.",
  "..jtijPPPPPPffffPPPffjtTj.",
  "..jtijPPPPPPPPPPPPPffjtTj.",
  "...jiijfPPPPPPPPPfffjtTj..",
  "...jtijjffPPPPPffffjttTj..",
  "...jtjttjjfffffffjjtjjTj..",
  "....jjtttijjjjjjjttTTjj...",
  ".....jjTtttttttttTTTjj....",
  ".......jjTTTTTTTTTjj......",
  ".........jjjjjjjjj........",
  "............jtj...........",
  "............jtj...........",
  "............jtj...........",
  "............jtj...........",
  "............jtj...........",
  "............jtj...........",
  "............jtj...........",
  "............jtj...........",
  "........jjjjitTjjj........",
  "......jjttttitTtttjj......",
  "......jTtttttttttTTTj.....",
  ".......jjTTTTTTTTTjj......",
  ".........jjjjjjjjj........",
];

// MALVA, the sorceress boss: tall black cloak, horned hood, pale shadowed face, claws (52 x 60)
const MALVA = [
  ".....jjjjjjj.............................jjjjjjj....",
  ".....jkkkQQkj...........................jkkkkDDj....",
  ".....jkkkkQkkj.........................jkkkkkDkj....",
  "......jkkkkQkkj.......................jkkkkkDDj.....",
  "......jkkkkkQQkjj......jjjjjjj......jjkkkkkDDkj.....",
  ".......jkkkkkQQkkjj..jjQQQQkkkjj..jjkkkkkkDDkj......",
  "........jkkkkkkQQkkjjfffffQQQkkkjjkkkkkkDDDkj.......",
  ".........jjkkkkkQQjQfffffffQQQkkkkjkkkDDDkjj........",
  "...........jkkkkkkjfffffffffQQQkkkjDDDDkkj..........",
  "............jjkkkjQfffffffffQQQQkkkjkkkjj...........",
  "..............jjjjQfjjjjjjjjjjjjjkkjjjj.............",
  "................jQQQjkkkkkkkkkkkjkkkj...............",
  "................jQQQjkkkkkkkkkkkjkkkj...............",
  "................jQQQjTTTTeeeTTTjkkkkj...............",
  "................jkkkjtitteeetittjkkkj...............",
  "................jkkkjzeeeeezzzzqjkkkj...............",
  ".................jkkjzzzzzzzzzzqjkkj................",
  ".................jkkjzzzccccczzqjkkj................",
  ".................jkkjzzccrrrccqqjkj.................",
  ".................jkkkjzccCCCccqjkkj.................",
  "jjj..............jkkkjqcCCCCCcqjkkj...............jj",
  "jeej..............jkkkjjcCCCcjjkkkj..............jej",
  "jwej..............jkkkkkjjjjjkkkkj...............jej",
  ".jwej.............jkkkkkkkkkkkkkkj..............jewj",
  ".jewej.............jjjkkkkkkkkjjj..............jewej",
  "..jeeejjjjjjjj.....jkkjjjkkjjjDDj......jjjjjjjjeeej.",
  "jjwweekjkkkkQQjjj.jkkQQfkjjkkjDDDj..jjjkkkkkkjkeewwj",
  "jeeeekkjjjjkkkkQQjjkkQfQkkDkkjDDDjjjkkkkkkjjjjkkeeej",
  "jjeeeekj...jjjkkkjkkkQfkkkDkkjDDDDjkkkkjjj...jkeeeej",
  "..jeeej.......jjjjkkQQfkkkDkkDjDDDjkjjj.......jeeej.",
  ".jeeej..........jkkkQjfkkkDkkDjDDDDj...........jeeej",
  ".jeej...........jkkQQjkkkkDkkkjDDDDj............jeej",
  "jeej...........jkkkQQjkkkkDkkkjDDDDDj............jej",
  "jeej...........jkkkQfjkkkkDkkkDjDDDDj............jej",
  "jjj............jkkQQfjkkkkDkkkDjDDDDj.............jj",
  "..............jkkkQQjkkkkkDkkkDjDDDDDj..............",
  "..............jkkQQfjkkkkkDkkkDjDDDDDj..............",
  ".............jkkkQQfjkkkkkDkkkDDjDDDDDj.............",
  ".............jkkkQQfjkkkkkDkkkDDjDDDDDj.............",
  "............jkkkQQQfjkkkkkDkkkkDjDDDDDDj............",
  "............jkkkQQffjkkkkkkDkkkDjDDDDDDj............",
  "...........jkkkkQQfQjkkkkkkDkkkDDjDDDDDDj...........",
  "...........jkkkQQQfQjkkkkkkDkkkDDjDDDDDDj...........",
  "...........jkkkQQffjkkkkkkkDkkkDDjDDDDDDj...........",
  "..........jkkkQQQfQjkkkkkkkDkkkDDjDDDDDDDj..........",
  "..........jkkkQQQfQjkkkkkkkDkkkDDDjDDDDDDj..........",
  ".........jkkkkQQffQjkkkkkkkDkkkDDDjDDDDDDDj.........",
  ".........jkkkQQQffkjkkkkkkkDkkkkDDjDDDDDDDj.........",
  "........jkkkkQQQfQkjkkkkkkkDkkkkDDjDDDDDDDDj........",
  "........jkkkQQQffQkjkkkkkkkDkkkkDDDjDDDDDDDj........",
  ".......jkkkkQQQffkkjkkkkkkkDkkkkDDDjDDDDDDDDj.......",
  ".......jkkkkQQQfQkjkkkkkkkkDkkkkDDDjDDDDDDDDj.......",
  "......jkkkkQQQffQkjkkkkkkkkDkkkkDDDjDDDDDDDDDj......",
  "......jkkkkQQQffQkjkkkkkkkkDkkkkDDDDjDDDDDDDDj......",
  "......jkkkkQQQfQkkjkkkkkkkkDkkkkkDDDjDDDDDDDDj......",
  ".....jkjjkQQQffQjjjkkkkkkkkDkkkkkDDjjDDDDDDjjDj.....",
  ".....jj..jjQQjjj..jjjkkkjjjjkkkjjDj.jjjDDjj..jj.....",
  "....j......jj........jjj....jjj..j.....jj......j....",
  "....................................................",
  "....................................................",
];

// swooper: flying corrupted human, wings spread (30 x 26)
const SWOOPER1 = [
  "..............................",
  "..............................",
  "..............................",
  "............jjjjjj............",
  "...........jfffQQQjj..........",
  "..........jfffffQQQj..........",
  ".j........jQwwfQQwwkj.......j.",
  ".jjj......jQweQQQwekj.....jjj.",
  ".jkQjj....jQQQQQQQkkj...jjDkj.",
  "jkkkQQjj...jQjcccjkj..jjDDkkkj",
  "jkkkkkQQjj.jjjrrcjjjjjDDkkkkkj",
  "jjjkkkkkQQjjfjrrcjkjDDkkkkkjjj",
  "...jkkkkkkjjfjrrcjkjkkkkkkj...",
  "...jkjkkkkjQfjrrcjkkjkkkjkj...",
  "..jjj.jkkkjQQfjjjQkkjkkj.jjj..",
  "..j...jkkjjQQQQQQQkkjkkj...j..",
  ".......jj.jQQQQQQDkkjjj.......",
  ".......j..jkQQQQQkkkj.j.......",
  "...........jDQQQkkDj..........",
  "...........jkkkkkkkj..........",
  "...........jjkkkkkjj..........",
  ".............jjjjj............",
  ".............j...j............",
  "............j.....j...........",
  "...........jj.....jj..........",
  "..............................",
];

// swooper: wings mid-flap (30 x 26)
const SWOOPER2 = [
  "..............................",
  "..jj......................jj..",
  "..jkjj..................jjkj..",
  "...jkkj.....jjjjjj.....jkkj...",
  "...jkkj....jfffQQQjj...jDkj...",
  "...jkkQj..jfffffQQQj..jkDkj...",
  "....jkkj..jQwwfQQwwkj.jDkj....",
  "....jkkkj.jQweQQQwekjjDkkj....",
  "...jkkkkj.jQQQQQQQkkjjDkkkj...",
  "..jkkkkkQj.jQjcccjkjjkDkkkkj..",
  "...jjjkkkj.jjjrrcjjjjDkkkjjj..",
  "......jkkkjjfjrrcjkjDkkjj.....",
  ".......jkkjjfjrrcjkjDkj.......",
  "........jkjQfjrrcjkkjj........",
  ".........jjQQfjjjQkkj.........",
  "..........jQQQQQQQkkj.........",
  "..........jQQQQQQDkkj.........",
  "..........jkQQQQQkkkj.........",
  "...........jDQQQkkDj..........",
  "...........jkkkkkkkj..........",
  "...........jjkkkkkjj..........",
  ".............jjjjj............",
  ".............j...j............",
  "............j.....j...........",
  "...........jj.....jj..........",
  "..............................",
];

// swooper: wings tucked, hat brim (30 x 26)
const SWOOPER3 = [
  "...........jjjjjjjjj..........",
  "...........jQQQQkkkj..........",
  "...........jkkkkkkkj..........",
  ".........jjjjjjjjjjjjj........",
  "...........jfffQQQjj..........",
  "..........jfffffQQQj..........",
  "..........jQwwfQQwwkj.........",
  "..........jQweQQQwekj.........",
  "..........jQQQQQQQkkj.........",
  "...........jQjcccjkj..........",
  "...........jjjrrcjjj..........",
  "...........jfjrrcjkj..........",
  ".....jjjjjjjfjrrcjkjjjjjj.....",
  ".....jkkkkjQfjrrcjkkjkkkj.....",
  ".....jQkkkjQQfjjjQkkjkkkj.....",
  ".....jkQkkjQQQQQQQkkjkkDkj....",
  "....jkkQkkjQQQQQQDkkjkkDkj....",
  "....jkkkQkjkQQQQQkkkjkDkkj....",
  "....jkkkQj.jDQQQkkDjjkDkkj....",
  ".....jjkjj.jkkkkkkkj.jkjj.....",
  ".......j...jjkkkkkjj..j.......",
  ".............jjjjj............",
  ".............j...j............",
  "............j.....j...........",
  "...........jj.....jj..........",
  "..............................",
];

// stomper: squat and wide (30 x 30)
const STOMPER1 = [
  "..............................",
  "..............................",
  "..............................",
  "..............................",
  "..............................",
  ".........jjjjjjjjjjjj.........",
  ".........jQQQQQQQQkkj.........",
  ".........jQwwQQQwwkDj.........",
  ".........jQweQQQwekDj.........",
  ".........jQQkkkkkkkDj.........",
  ".........jQQkkkkkkkDj.........",
  ".........jQQrrrrrkkDj.........",
  "........jjQQcCCCckkDj.........",
  "......jjQjkkkkkkkkkDjjjj......",
  ".....jkkQjjjjjjjjjjjjkkj......",
  "......jkkkkkkkkkkkkkkkkj......",
  "jj....jQQkkkkkkkkkkkkDDj....jj",
  "jkjjjjjQQQkDkkkkkkkkkDDjjjjjkj",
  "jkkkkkjQQQkDkkDkkkkkkDDjkkkkkj",
  "jkjjjjjQQQkkDkDkkDkkkDDjjjjjkj",
  "jj....jQQQkkDkkDkkDkkDDj....jj",
  "......jQQQkkDkkDkkDkkDDj......",
  "......jQQQkkkkkkkkkkkDDj......",
  "......jQQQkkkkkkkkkkkDDj......",
  "......jjjjjjjjjjjjjjjjjj......",
  "........jQkj......jQkj........",
  "........jQkj......jQkj........",
  "........jQkj......jQkj........",
  "........jDDj......jDDj........",
  "........jjjj......jjjj........",
];

// stomper: tall and narrow (30 x 30)
const STOMPER2 = [
  "..............................",
  "...........jjjjjjjj...........",
  "...........jQQQQkkj...........",
  "...........jQffQkDj...........",
  "...........jwQQQwwj...........",
  "...........jeQkkwej...........",
  "...........jQQkkkDj...........",
  "...........jQQkkkDj...........",
  "...........jQQkkkDj...........",
  "...........jrrrrrDj...........",
  "...........jcCCCcDj...........",
  ".........jjjkkkkkDjj..........",
  ".........jkjjjjjjjjj..........",
  ".........jkkkkkkkkkj..........",
  "jj........jkkkkkkkDj........jj",
  "jkjjjjjjjjjQQQkDkDDjjjjjjjjjkj",
  "jkkkkkkkkkjQQQkDkDDjkkkkkkkkkj",
  "jkjjjjjjjjjQQQkDkDDjjjjjjjjjkj",
  "jj........jQQQkDkDDj........jj",
  "..........jQQQkkDDDj..........",
  "..........jQQQkkDDDj..........",
  "..........jQQQkkDDDj..........",
  "..........jQQQkkDDDj..........",
  "..........jQQQkkkDDj..........",
  "..........jQQQkkkDDj..........",
  "..........jjjjjjjjjj..........",
  "............jQkQkj............",
  "............jQkQkj............",
  "............jDDDDj............",
  "............jjjjjj............",
];

// stomper: big square head (30 x 30)
const STOMPER3 = [
  "..............................",
  "......jjjjjjjjjjjjjjjjjj......",
  "......jQQQQQQQQQQQQQQkkj......",
  "......jQffQQQQQQQQQQQkDj......",
  "......jQQQQQQQQQQQQQQkDj......",
  "......jQQkkkkkkkkkkkkkDj......",
  "......jQQkkkkkkkkkkkkkDj......",
  "......jQQkkwwkkkwwkkkkDj......",
  "......jQQkkwekkkwekkkkDj......",
  "......jQQkkkkkkkkkkkkkDj......",
  "......jQQkkkkkkkkkkkkkDj......",
  "......jQQkkkkkkkkkkkkkDj......",
  "......jQQkkkkkkkkkkkkkDj......",
  "......jQQkkkkkkkkkkkkkDj......",
  "......jQQkkrrrrrrrkkkkDj......",
  "......jQQkkcCwCwCckkkkDj......",
  "......jkkkkcCCCCCckkkkDj......",
  "......jjjjjjjjjjjjjjjjjj......",
  ".........jkkkkkkkkkj..........",
  "jj........jkkkkkkkDj........jj",
  "jkjjjjjjjjjQQQkDkDDjjjjjjjjjkj",
  "jkkkkkkkkkjQQQkkDDDjkkkkkkkkkj",
  "jkjjjjjjjjjQQQkkDDDjjjjjjjjjkj",
  "jj........jQQQkkkDDj........jj",
  "..........jQQQkkkDDj..........",
  "..........jjjjjjjjjj..........",
  "............jQkQkj............",
  "............jQkQkj............",
  "............jDDDDj............",
  "............jjjjjj............",
];

// the Hollow's gate seen from town: jagged stone spire with a glowing arch (48 x 40)
const HOLLOWGATE = [
  "................................................",
  "................................................",
  "................................................",
  ".......................j........................",
  "......................jj........................",
  "......................jqj....jj.................",
  "......................jqj...jqj.................",
  "......................jzqj.jqej.................",
  ".....................jzzQqjqqqqj................",
  ".....................jzzQqqqqqqj................",
  ".....................jzzQqqqqqqj................",
  ".....................jzzzQqqqqqqj...............",
  ".................j..jzzzzQqqqqqqqj..............",
  "................jqj.jzzzzQqqqqqqqqj.............",
  "................jqqjqzzzzzQqqqqqqQqj............",
  "................jzqqzzjjjjQqqqqqQQQqj...........",
  "..............jjzzzqjjkkkkjjjqqqQQQQj...........",
  "...............jjjjjjjjkjjjkjjjjjjQQQj..........",
  "..............jzzjjkjqjkjqjkjqjQjQQQQj..........",
  "..............jzzjkkkjkDDjkkkjkjjQQQQj..........",
  ".........j....jzjjkkkjDDDjDkkjkjjQQQkQj.........",
  "........jqjj.jzjkkkkDjDDDjDDkjkkjQQQkQj.........",
  "........jqqqjqzjkkkDDjDDDDDDDjkkjQQQkQj.........",
  ".......jqzzqqzjkkkDDDDDDPDDDDDkkkjQQQkQj........",
  ".......jzQzzzzjkkkDDDDDDDDDDDDkkkjQQQkQqj.......",
  "......jqzQzzzjkkkDDDDDDDDDDDfDDkkkjQQkQQqjj.....",
  "......jzzzQzzjkkkDDDfDDDDDDDDDDkkkjQQkQQQqqj....",
  ".....jzzzzQzzjkkDDDDDDDDDDDDDDDDkkjQQkQQQQQqj...",
  "....jqzzzzQzzjkkDDDDDDDDDDDDDDDDkkjQQQkQQQQQj...",
  "...jqzzzzzQzzjkkDDDDDfffffffDDDDkkjQQQkQQQQQQj..",
  "..jqqzzzzzzQzjkkDDDfffffffffffDDkkjQQQkQQQQQQj..",
  "..jqqzzzzzzQzjkkDDfffffffffffffDkkjQQQQQQQQQQj..",
  ".jqqzzzzzzzQzjkkDDfffffffffffffDkkjQQQQQQQQQQQj.",
  ".jqqzzzzzzzzQjkkDfffffPPPPPfffffkkjQQQQQQQQQQQj.",
  ".jqqzzzzzzzzQjkkDfffPPPPPPPPPfffkkjQQQQQQQQQQQj.",
  ".jqqzzzzzzzzzjkkDffPPPPPPPPPPPffkkjQQQQQQQQQQQj.",
  ".jqqzzzzzzzzzjkkDDfPPPpppPPPPPfDkkjQQQQQQQQQQQj.",
  "jqqzzzzzzzzzzjkkDDfPPpppppPPPPfDkkjQQQQQQQQQQQj.",
  "jjjjjjjjjjjjjjjjjjjjjPpppPPPjjjjjjjjjjjjjjjjjjj.",
  "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
];

// the villain king: three-point crown with gems, purple cape, cruel grin, corrupting hand raised (20 x 26)
const KING = [
  "....jtj.jtj.jtj.....",
  "....jtrjjtrjjtrj....",
  "....jtitttttttTj....",
  ".n..jjTTTTTTTTjj....",
  "p.p.jjhssssssssjj...",
  "jsjsjsjjsssssjjsj...",
  "jssjjsjjjsssjjjsj...",
  "jssjjsjwjsssjwjsj...",
  "jssjjsjjjsssjjjsj...",
  "jssjjsssssjssssSj...",
  ".jkkjsjjjjjjjjjsj...",
  ".jkkjssjwwwwwjssj...",
  ".jkkjSssjjjjjssSj...",
  ".jkkjPPjjdddjjPPj...",
  ".jkkjpPkkjdjkkkkPPj.",
  "..jjjpPkkkkkkkkkPPj.",
  "....jpPkkkrkkkkkPPj.",
  "....jPPkkkkkkkkkPPj.",
  "....jPPjkkkkkkkjPPj.",
  "....jPPPjkkkkkjPPPj.",
  "....jPPPjQQQQQjPPPj.",
  "....jPPPjkkkkkjPPPj.",
  "....jjjjjkkjkkjjjjj.",
  "........jkkjkkj.....",
  ".......jkkkjjkkkj...",
  ".......jjjjjjjjjj...",
];

// a scared townsman: brown hair, green shirt, wide worried eyes, hands up (20 x 26)
const MAN = [
  ".......jjjjjjj......",
  ".....jjuuuuuuujj....",
  "....juuuuuuuuuuUj...",
  "....jujjjjjjjjjjuj..",
  "....jjhssssssssjj...",
  "....jsssssssssssj...",
  "....jssjjsssjjssj...",
  "....jsjjsssssjjsj...",
  "....jsjjjsssjjjsj...",
  "....jsjwjsssjwjsj...",
  "....jsjjjsssjjjsj...",
  "....jsxxsssssxxsj...",
  "....jssssjjjssssj...",
  "....jSsssjCjsssSj...",
  ".jsj.jSSSSSSSSSj.jsj",
  ".jsj..jjSSSSSjj..jsj",
  ".jsjjjjgggLgggGjjjsj",
  ".jssjggggggggggGjssj",
  "..jjjggggggggggGjjj.",
  "....jjgggggggGGjj...",
  ".....jgggggggGGj....",
  ".....jgggggggGGj....",
  ".....jUUUUUUUUUj....",
  "......jssjjssj......",
  ".....jkkkjjkkkj.....",
  ".....jjjjjjjjjj.....",
];
// ---------------------------------------------------------------- scenery

// round cartoon tree with fruit and a highlight
const TREE = [
  "......jjjjjj......",
  "....jjGGgggGjj....",
  "...jGGggVVgggGj...",
  "..jGggVVggggggGj..",
  "..jGggVgggrggggj..",
  ".jGgggggggggggGGj.",
  ".jGggrgggggggrgGj.",
  ".jGggggggggggggGj.",
  ".jGGgggggrgggGGGj.",
  "..jGGgggggggGGGj..",
  "...jGGGGgGGGGGj...",
  "....jjGGGGGjjj....",
  "......jjUuUj......",
  ".......jUuUj......",
  ".......jUuUj......",
  "......jUUuUUj.....",
  "......jjjjjjj.....",
];

const HOUSE = [
  "..............jRRRRRRRRRRRRRRRRRj.............",
  "............jjRRXXRRRRRRRRRRRRRRRjj...........",
  "..........jjRRRXRRRRRRRRRRRRRRRRRRRjj.........",
  "........jjRRRRRRRRRRRRRRRRRRRRRRRRRRRjj.......",
  "......jjRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRjj.....",
  "....jjRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRjj...",
  "..jjrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrjj.",
  "..jvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvj.",
  "..jvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvj.",
  "..jvvvvjbbbbbjvvvvvvvvvvvvvvvvvvvjbbbbbjvvvvj.",
  "..jvvvvjlwbbbjvvvvvvvvvvvvvvvvvvvjlwbbbjvvvvj.",
  "..jvvvvjbbbbbjvvvvvvvjUUUUUjvvvvvjbbbbbjvvvvj.",
  "..jvvvvjjjjjjjvvvvvvvjUuuuUjvvvvvjjjjjjjvvvvj.",
  "..jvvvvvvvvvvvvvvvvvvjUutuUjvvvvvvvvvvvvvvvvj.",
  "..jvvvvvvvvvvvvvvvvvvjUuuuUjvvvvvvvvvvvvvvvvj.",
  "..jvvvvvvvvvvvvvvvvvvjUuuuUjvvvvvvvvvvvvvvvvj.",
  "..jjjjjjjjjjjjjjjjjjjjUuuuUjjjjjjjjjjjjjjjjjj.",
];

const WAGON = [
  "............jttttttttttttttttttttj............",
  "..........jjtrtrtrtrtrtrtrtrtrtrtjj...........",
  "........jjrtrtrtrtrtrtrtrtrtrtrtrtrjj.........",
  "........jrrrrrrrrrrrrrrrrrrrrrrrrrrrrj........",
  "........jrttrttrttrttrttrttrttrttrttrj........",
  "........jrttrttrttrttrttrttrttrttrttrj........",
  "........jrrrrrrrrrrrrrrrrrrrrrrrrrrrrj........",
  "........jrrrjkkkkkkjrrrrrrrrjkkkkkkjrrj.......",
  "........jrrrjkkllkkjrrrrrrrrjkkllkkjrrj.......",
  "........jrrrjkkkkkkjrrrrrrrrjkkkkkkjrrj.......",
  "........jrrrjjjjjjjjrrrrrrrrjjjjjjjjrrj.......",
  "........jRRRRRRRRRRRRRRRRRRRRRRRRRRRRRj.......",
  ".....jjjUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUjjj....",
  "........jQQQQj....................jQQQQj......",
  ".......jQQqzQQj..................jQQqzQQj.jjj.",
  ".......jQQQQQQj..................jQQQQQQjjQqQj",
  "........jjjjjj....................jjjjjj.jjjj.",
];

const TENT = [
  "......................jtj.....................",
  "......................jtj.....................",
  "....................jjrrrjj...................",
  "..................jjrrXrrrrjj.................",
  "................jjrttrrttrrttjj...............",
  "..............jjrrttrrttrrttrrrjj.............",
  "............jjrrrrttrrttrrttrrrrrjj...........",
  "..........jjrrrrrrttrrttrrttrrrrrrrjj.........",
  "........jjrrrrrrrrttrrttrrttrrrrrrrrrjj.......",
  "......jjrrrrrrrrrrttrrttrrttrrrrrrrrrrrjj.....",
  "....jjrrrrrrrrrrrrttrrttrrttrrrrrrrrrrrrrjj...",
  "..jjrrrrrrrrrrrrrrttrrttrrttrrrrrrrrrrrrrrrjj.",
  "..jrttrrttrrttrrttrrttrrttrrttrrttrrttrrttrrj.",
  "..jrttrrttrrttrrttrrttrrttrrttrrttrrttrrttrrj.",
  "..jrttrrttrrttrrttrjjjjjjjjjrrttrrttrrttrrttrj",
  "..jrttrrttrrttrrttrjkkkkkkkjrrttrrttrrttrrttrj",
  "..jrttrrttrrttrrttrjkkkkkkkjrrttrrttrrttrrttrj",
  "..jjjjjjjjjjjjjjjjjjkkkkkkkjjjjjjjjjjjjjjjjjjj",
];

// wrapped present with a big bow (16 x 16)
const PRESENT = [
  "....jjj....jjj..",
  "...jmmnj..jnmmj.",
  "...jmmmmjjmmmmj.",
  "....jjmmmmmmjj..",
  "..jjjjjjmmjjjjjj",
  ".jbbbbbbjmjbbbbbj",
  ".jblbbbbjmjbbbbbj",
  ".jbbbbbbjmjbbbbbj",
  ".jmmmmmmmmmmmmmmj",
  ".jbbbbbbjmjbbbbbj",
  ".jbbbbbbjmjbbbbbj",
  ".jbbbbbbjmjbbbbbj",
  ".jBBBBBBjmjBBBBBj",
  ".jBBBBBBjmjBBBBBj",
  ".jjjjjjjjjjjjjjjj",
];

// the sword held up on pickup (10 x 28): bright blade, gold guard, blue gem
const SWORD = [
  "....jj....",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  "...jwej...",
  ".jjjttjjj.",
  "jtttttttttj",
  ".jjjuujjj.",
  "...juuj...",
  "...juuj...",
  "...juuj...",
  "...juuj...",
  "..jtlbtj..",
  "..jtbbtj..",
  "...jttj...",
  "....jj....",
];

// ---------------------------------------------------------------- friends and party (hand-drawn)
// Pip, Zed, Bruno and Bloop join the hero's party. Same chibi rules as the
// family: navy outline, three tones lit from the top left, big eyes with a
// catchlight, rosy cheeks. The *_B variants are the party seen from behind
// for the battle screen; hair and colours carry the identity.

// pip: potion maker, lilac hair in two buns, goggles pushed up, apron with a bottle, green vial held out (20 x 26)
const PIP = [
  ".jjj..jjjjjjjj..jjj.",
  "jpppjjppppNNppjjpppj",
  "jpNpjpNNpppppppjpNpj",
  "jPPPjpjjjjjjjjjjPPPj",
  "....jpjwajjjaajpj...",
  "....jpjjjjjjjjjpj...",
  "....jjhssssssssjj...",
  "....jsssssssssssj...",
  "....jsjjjsssjjjsj...",
  "....jsjwjsssjwjsj...",
  "....jsjjjsssjjjsj...",
  "....jsxxsssssxxsj...",
  "....jSssjssssjssj...",
  ".jjjjjSSsjjjjsSj....",
  ".juj..jjSSSSSjj.....",
  "jjLjjjjPPPPPPPjj....",
  "jLVLjsPPwwwwwPPsj...",
  "jLLLjsPPwwGwwPPsj...",
  "jsssjsPPwwgwwPPsj...",
  ".jjjjj.PwwwwwP.sj...",
  ".......jPwwwPj.jj...",
  "......jPPPPPPPj.....",
  ".......jssjssj......",
  "......jjjjjjjjj.....",
  ".....juuujjjuuuj....",
  ".....jjjjjjjjjjj....",
];

// zed: spiky dark-blue hair, black jacket over a white tee, cyan lightsaber with a white core and a faint glow, toothy grin (20 x 26)
const ZED = [
  "....j....j....j.....",
  "...jBj..jBj..jZj.44.",
  "..jBBBjjBBZjjZZHjaa4",
  "..jBBBBZZZZZZZZH4wa4",
  "...jZjjjjjjjjjZj4wa4",
  "...jZhssssssssjj4wa4",
  "...jsssssssssssj4wa4",
  "...jsjjjsssjjjsj4wa4",
  "...jsjwjsssjwjsj4wa4",
  "...jsjjjsssjjjsj4wa4",
  "...jsxxsssssxxsj4wa4",
  "...jSssjwwwwjssj4wa4",
  "....jSSsjjjjsSj4wa4.",
  ".....jjSSSSSjj.4wa4.",
  "....jjkkkkkkkjjjQej.",
  "...jskkQwwwQkksjssj.",
  "...jskkQwwwQkkkjjjj.",
  "...jskkkwwwkkkj.....",
  "...jskkkwwwkkkj.....",
  "...js.kkkkkkkj......",
  "...jj.jQQQQQj.......",
  "......jQQjQQj.......",
  "......jQQjQQj.......",
  ".....jjjjjjjjj......",
  "....jkkkjjjkkkj.....",
  "....jjjjjjjjjjj.....",
];

// bruno: very muscular karate boy, white gi and black belt, red headband, square shoulders, thick arms with fists up, determined brows (24 x 27)
const BRUNO = [
  "........jjjjjjjj........",
  "......jjddddddddjj......",
  ".....jddfddddddddddj....",
  ".....jrrrrrrrrrrrrjrj...",
  ".....jRrrrrrrrrrrRj.jrj.",
  ".....jjhsssssssssjj.jj..",
  ".....jssjjssssjjssj.....",
  ".....jsjjjssssjjjsj.....",
  ".....jsjwjssssjwjsj.....",
  ".jjj.jsjjjssssjjjsj.jjj.",
  "jsssjjsxxssssssxxsjjsssj",
  "jssSjjSsssjjjjsssSjjSssj",
  ".jsSj.jSSssssssSSj.jsSj.",
  ".jssj..jjSSSSSSjj..jssj.",
  ".jssjjjjjjjjjjjjjjjjssj.",
  ".jssjwwwwessssewwwwjssj.",
  ".jsSjwwwwwessewwwwwjsSj.",
  ".jsSjwwwwwweewwwwwwjsSj.",
  ".jjjjwwwwwwwwwwwwwwjjjj.",
  "....jkkkkkkQQkkkkkkj....",
  "....jwwwwwkwwkwwwwwj....",
  "....jwwwwwkwwkwwwwwj....",
  "....jwwwwwwjjwwwwwwj....",
  "....jWWWWWWjjWWWWWWj....",
  "....jjjjjjjjjjjjjjjj....",
  "...jsssssssjjsssssssj...",
  "...jjjjjjjjjjjjjjjjjj...",
];

// bloop: a round pale-pink creature that is mostly head, big round nose, dot eyes, thick brows, one hair curl with a red bow, no arms, stubby feet (22 x 20)
const BLOOP = [
  "........jrrjrrj.......",
  "........jRrjrRj.......",
  "..........jdj.........",
  "........jjjdjjj.......",
  "......jj3333333jj.....",
  "....jj3hh33333336jj...",
  "...j33hh3333333366j...",
  "..j33h3333333333366j..",
  ".j333jjj333333jjj366j.",
  ".j3333j33333333j3366j.",
  "j33333333jjjj33333666j",
  "j3333333jhsssj3333666j",
  "j333333jshssssj333666j",
  "j333333jSsssSSj333666j",
  ".j333333jSSSSj333666j.",
  ".j3333333jjjj3336666j.",
  "..j3333333333336666j..",
  "...j66666666666666j...",
  "....jssj......jssj....",
  "....jjjj......jjjj....",
];

// rock: grey cartoon boulder with a highlight and two cracks (18 x 14)
const ROCK = [
  "......jjjjjj......",
  "....jjzzqqqqjj....",
  "...jzzzqqqqqqqj...",
  "..jzzqqqqqqqqqQj..",
  ".jzqqqqqjqqqqqQQj.",
  ".jqqqqqjqqqqqqQQj.",
  "jqqqqqjqqqqqqqQQQj",
  "jqqqqqqqqqjqqqQQQj",
  "jqqqqqqqqjqqqqQQQj",
  "jQqqqqqqqqqqqqQQQj",
  ".jQqqqqqqqqqqQQQj.",
  ".jQQqqqqqqqQQQQQj.",
  "..jjQQQQQQQQQQjj..",
  "....jjjjjjjjjj....",
];

// rock2: wider two-lobed boulder (24 x 16)
const ROCK2 = [
  "........jjjjjj..........",
  "......jjzzqqqqjj........",
  ".....jzzzqqqqqqqj..jjj..",
  "....jzzqqqqqqqqqqjjqqqj.",
  "...jzqqqqqqjqqqqqqqqqqQj",
  "..jzqqqqqqjqqqqqqqqqqQQj",
  ".jqqqqqqqjqqqqqqqqqqQQQj",
  ".jqqqqqqjqqqqqqjqqqqQQQj",
  "jqqqqqqqqqqqqqjqqqqQQQQj",
  "jqqqqqqqqqqqqqqjqqqQQQQj",
  "jQqqqqqqqqqqqqqqqqqQQQQj",
  "jQqqqqqqqqqqqqqqqqQQQQQj",
  ".jQQqqqqqqqqqqqqqQQQQQj.",
  ".jQQQqqqqqqqqqqQQQQQQQj.",
  "..jjQQQQQQQQQQQQQQQQjj..",
  "....jjjjjjjjjjjjjjjj....",
];

// bush: round green bush with a highlight and red berries (18 x 16)
const BUSH = [
  "....jjj...jjjj....",
  "..jjgVVjjjgLggjj..",
  ".jgVVgggggggggggj.",
  ".jgVgggggggrggggj.",
  "jgggggggggggggGGGj",
  "jggggrgggggggggGGj",
  "jggggggggggrggGGGj",
  "jgggggggggggggGGGj",
  "jgggrgggggggggGGGj",
  "jGggggggrggggGGGGj",
  "jGgggggggggggGGGGj",
  ".jGGgggggggGGGGGj.",
  ".jGGGgggrggGGGGGj.",
  "..jGGGGGGGGGGGGj..",
  "...jjGGGGGGGGjj...",
  ".....jjjjjjjj.....",
];

// sign: small wooden signpost (14 x 16)
const SIGN = [
  ".jjjjjjjjjjjj.",
  "j7uuuuuuuuuuUj",
  "j7uuuuuuuuuuUj",
  "j7uUUUUUUUUuUj",
  "j7uuuuuuuuuuUj",
  "j7uUUUUUUuuuUj",
  "j7uuuuuuuuuuUj",
  "jUUUUUUUUUUUUj",
  ".jjjjjjjjjjjj.",
  ".....juuUj....",
  ".....juuUj....",
  ".....juuUj....",
  ".....juuUj....",
  ".....juuUj....",
  ".....juuUj....",
  ".....jjjj.....",
];

// hero from behind: blonde hair, white tee, blue shorts, sneakers (24 x 28)
const HERO_B = [
  "........jjjjjjjj........",
  "......jjyyiiyyyyjj......",
  ".....jyyiiiyyyyyyyj.....",
  "....jyyiiyyyyyyyyyyj....",
  "....jyyyyyyyyyyyyYyj....",
  "...jyYyyyyyyyyyyYYyyj...",
  "...jyYyyyyyyyyyyYYyyj...",
  "...jyyyyyyyyyyyyyYYyj...",
  "...jyyyyyyyyyyyyyYYyj...",
  "...jyyyyyyyyyyyyyyYYYj..",
  "...jsyyyyyyyyyyyyyYYsj..",
  "....jYyyyyyyyyyyyYYYj...",
  "....jsjYYYYYYYYYYYjsj...",
  ".....jSSsssssssssSSj....",
  "......jjSSSSSSSSSjj.....",
  ".....jjwwwwvvwwwwwjj....",
  "....jswwwwwvvwwwwwwsj...",
  "....jswwwwwwwwwwwwwsj...",
  "....js.wwwwwwwwwwww.sj..",
  "....jj.jWWWWWWWWWWj.jj..",
  ".......jbbbblbbbbbj.....",
  ".......jbbbbbbbbbbj.....",
  ".......jBBBBBBBBBBj.....",
  ".......jssssjjssssj.....",
  ".......jSssj..jssSj.....",
  "......jjjjjj..jjjjjj....",
  ".....jkkkkkkjjkkkkkkj...",
  ".....jwwwwwwjjwwwwwwj...",
];

// pip from behind: lilac buns, goggle strap, purple dress with the apron bow at the back (20 x 24)
const PIP_B = [
  ".jjj..jjjjjjjj..jjj.",
  "jpppjjppppNNppjjpppj",
  "jpNpjpNNpppppppjpNpj",
  "jPPPjppppppppppjPPPj",
  "....jpkkkkkkkkkPj...",
  "....jpppppppppPPj...",
  "....jspppppppPPsj...",
  "....jspppppppPPsj...",
  "....jpppppppppPPj...",
  "....jPPpppppppPPj...",
  ".....jPPPPPPPPPj....",
  "......jjSSSSSjj.....",
  ".....jjPPPPPPPjj....",
  "....jsPPPPPPPPPsj...",
  "....jsPPPPPPPPPsj...",
  "....jsPPwwjwwPPsj...",
  "....js.PPwjwPP.sj...",
  "....jj.jPwPwPj.jj...",
  "......jPPPPPPPj.....",
  ".......jssjssj......",
  ".......jssjssj......",
  "......jjjjjjjjj.....",
  ".....juuujjjuuuj....",
  ".....jjjjjjjjjjj....",
];

// zed from behind: spiky dark-blue hair, black jacket, saber raised on his left (20 x 24)
const ZED_B = [
  ".....j....j....j....",
  ".44.jBj..jBj..jZj...",
  "4aajBBBjjBBZjjZZHj..",
  "4aw4BBBBZZZZZZZZHHj.",
  "4aw4jBBZZZZZZZZHj...",
  "4aw4jBZZZZZZZZZHj...",
  "4aw4jsZZZZZZZZHsj...",
  "4aw4jsZZZZZZZZHsj...",
  "4aw4jZZZZZZZZZHHj...",
  "4aw4.jHZZZZZZZHj....",
  "4aw4..jjSSSSSjj.....",
  "4aw4.jjkkkkkkkjj....",
  "4aw4jskkkkkkkkksj...",
  "4aw4jskkkkkkkkksj...",
  "jeQjjskkkkkkkkksj...",
  "jssjjskkkkkkkkksj...",
  "jjjjjj.kkkkkkk.sj...",
  ".......jQQQQQj.jj...",
  ".......jQQjQQj......",
  ".......jQQjQQj......",
  ".......jQQjQQj......",
  "......jjjjjjjjj.....",
  ".....jkkkjjjkkkj....",
  ".....jjjjjjjjjjj....",
];

// bruno from behind: headband knot and tails, white gi back, belt, fists up (24 x 24)
const BRUNO_B = [
  "........jjjjjjjj........",
  "......jjddddddddjj......",
  ".....jddfddddddddddj....",
  ".....jrrrrrrrrrrrrj.....",
  ".....jRrrrrjjrrrrRj.....",
  ".....jdddddrrdddddj.....",
  ".....jsddddrrddddsj.....",
  ".....jsddddrrdddDsj.....",
  ".....jddddddddddDDj.....",
  ".jjj..jDDddddddDDj..jjj.",
  "jsssj..jjSSSSSSjj..jsssj",
  "jssSjjjjjjjjjjjjjjjjSssj",
  ".jssjwwwwwwwwwwwwwwjssj.",
  ".jsSjwwwwwwwwwwwwwwjSsj.",
  ".jsSjwwwwwwwwwwwwwwjSsj.",
  ".jjjjwwwwwwwwwwwwwwjjjj.",
  "....jkkkkkkkkkkkkkkj....",
  "....jwwwwwwwwwwwwwwj....",
  "....jwwwwwwjjwwwwwwj....",
  "....jwwwwwwjjwwwwwwj....",
  "....jWWWWWWjjWWWWWWj....",
  "....jjjjjjjjjjjjjjjj....",
  "...jSSSSSSSjjSSSSSSSj...",
  "...jjjjjjjjjjjjjjjjjj...",
];

// bloop from behind: the round body, the curl and bow, stubby feet (22 x 20)
const BLOOP_B = [
  "........jrrjrrj.......",
  "........jRrjrRj.......",
  "..........jdj.........",
  "........jjjdjjj.......",
  "......jj3333333jj.....",
  "....jj3hh33333336jj...",
  "...j33hh3333333366j...",
  "..j33h3333333333366j..",
  ".j333333333333336666j.",
  ".j333333333333336666j.",
  "j33333333333333336666j",
  "j33333333333333336666j",
  "j33333333333333336666j",
  "j33333333333333336666j",
  ".j333333333333336666j.",
  ".j333333333333336666j.",
  "..j3333333333336666j..",
  "...j66666666666666j...",
  "....jssj......jssj....",
  "....jjjj......jjjj....",
];

// ---------------------------------------------------------------- end friends

window.SPRITES = {
  hero: HERO, hero_sword: HERO_SWORD, hero_giant: HERO_GIANT, mom: MOM, dad: DAD, sis: SIS, bro: BRO,
  cat1: CAT_ORANGE, cat2: CAT_GREY,
  elder: ELDER, kid: KID, dog: DOG,
  bugon: BUGON, lygon: LYGON,
  chompo: CHOMPO, zagg: ZAGG, skitter: SKITTER, wibblo: WIBBLO, redstack: REDSTACK, boxor: BOXOR, cavemouth: CAVEMOUTH,
  orb: ORB, malva: MALVA, swooper1: SWOOPER1, swooper2: SWOOPER2, swooper3: SWOOPER3,
  stomper1: STOMPER1, stomper2: STOMPER2, stomper3: STOMPER3, hollowgate: HOLLOWGATE, king: KING, man: MAN,
  tree: TREE, house: HOUSE, wagon: WAGON, tent: TENT, present: PRESENT, sword: SWORD,
  pip: PIP, zed: ZED, bruno: BRUNO, bloop: BLOOP, rock: ROCK, rock2: ROCK2, bush: BUSH, sign: SIGN,
  hero_b: HERO_B, pip_b: PIP_B, zed_b: ZED_B, bruno_b: BRUNO_B, bloop_b: BLOOP_B,
};
window.pixels = pixels;
